@startuml
'https://plantuml.com/class-diagram

interface Controller {
    +Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error)
    +SetupWithManager(mgr ctrl.Manager) error
}

class visitorsAppController {
    -client Client
	-scheme *runtime.Scheme
	-components []VisitorsAppComponent
	-visitors []ReconcileVisitor
    +Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error)
    +SetupWithManager(mgr ctrl.Manager) error
}

class visitorsAppController implements Controller

interface VisitorsAppComponent {
    +AcceptReconcileVisitor(v ReconcileVisitor)
}

class frontendComponent {
    +GetDeployment()
    +GetService()
    +GetSecret()
    +AcceptReconcileVisitor(v ReconcileVisitor)
}
class frontendComponent implements VisitorsAppComponent

class backendComponent {
    +GetDeployment()
    +GetService()
    +GetSecret()
    +AcceptReconcileVisitor(v ReconcileVisitor)
}
class backendComponent implements VisitorsAppComponent

class mysqlComponent {
    +GetDeployment()
    +GetService()
    +GetSecret()
    +AcceptReconcileVisitor(v ReconcileVisitor)
}
class mysqlComponent implements VisitorsAppComponent

visitorsAppController "1" o-->  "many" VisitorsAppComponent
visitorsAppController "1" o-->  "many" ReconcileVisitor

interface ReconcileVisitor {
    +ReconcileFrontend()
    +ReconcileBackend()
    +ReconcileBackend()
}

class deploymentReconcileVisitor {
    -client Client
    +ReconcileFrontend()
    +ReconcileBackend()
    +ReconcileBackend()
}

class serviceReconcileVisitor {
    -client Client
    +ReconcileFrontend()
    +ReconcileBackend()
    +ReconcileBackend()
}

class secretReconcileVisitor {
    -client Client
    +ReconcileFrontend()
    +ReconcileBackend()
    +ReconcileBackend()
}

class deploymentReconcileVisitor implements ReconcileVisitor
class serviceReconcileVisitor implements ReconcileVisitor
class secretReconcileVisitor implements ReconcileVisitor

ReconcileVisitor ..> frontendComponent
ReconcileVisitor ..> backendComponent
ReconcileVisitor ..> mysqlComponent

@enduml
